spring.application.name=great-amazon-website
server.port=8081
//spring.h2.console.enabled=true ---> Using SQL instead of H2

spring.datasource.url=jdbc:postgresql://localhost:5432/great_amazon_website
spring.datasource.username=bobbym.moneyjr.
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true